version: "3"

services:
  chrome:
    image: selenium/node-chrome:108.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=3
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "7900-7902:7900"
        # assigning the vnc ports for multiple scale containers

  firefox:
    image: selenium/node-firefox:108.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=3
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "7903-7905:7900"

  selenium-hub:
    image: selenium/hub:4.7.2
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"


#cd docker
#docker-compose -f docker-compose-hubNode.yml up -d
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
